baseURL = 'https://0x1do.github.io/'
languageCode = 'en-us'
title = "Ido's blog"
theme = "LoveIt"

languageName = "English"

# Author config
[author]
  name = "Ido Schwartzer"
  email = "ido.schwartzer@gmail.com"
  link = "https://github.com/0x1do"


# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Posts"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# Home page config
[params.home]
  # LoveIt NEW | 0.2.0 amount of RSS pages
  rss = 10
  # Home page profile
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "https://github.com/0x1do/0x1do.github.io/blob/main/content/me2.jpg?raw=true"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = "0x1do"
    # subtitle shown in home page (HTML format is supported)
    subtitle = "some writeups and sh1t... check out my About page"
    description = "My personal portfolio, showcasing me and my achievements in cybersecurity, as well as a blog where I share CTF write-ups, penetration testing insights, and other security-related content. 🚀 "
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

# Social config about the author
[params.social]
  GitHub = "0x1do"
  Linkedin = "https://www.linkedin.com/in/ido-schwartzer%E2%80%AC%E2%80%8F-72ba122b8/"
  Email = "ido.schwartzer@gmail.com"


# Header config
[params.header]
  # desktop header mode ["fixed", "normal", "auto"]
  desktopMode = "fixed"
  # mobile header mode ["fixed", "normal", "auto"]
  mobileMode = "auto"
  #  Header title config
  [params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "Ido's Blog."
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    #  whether to use typeit animation for title name
    typeit = false
